sudo: required
# Tells Travis we need a copy of docker ready
services:
  - docker

# The tag is only used in this build so can be anything but
# conventionally, the formal tag syntax is used
before_install:
  - docker build -t jerrylerman/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jerrylerman/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-375077564851"
  bucket_path: "docker-react"

  # Only deploy if the master branch is updated!!
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"